[PaddlePaddle Hackathon] Add test of paddle.nn.CosineSimilarity
PaddlePaddle/PaddleTest pull request #223
Opened 2021-10-08 16:13 UTC by gsq7474741

PR types
New features

PR changes
api.nn

Describe
Add test of paddle.nn.CosineSimilarity.

2021-10-08 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=223) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=223) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleTest?pullRequest=223) it.</sub>

2021-10-09 07:06 UTC, gsq7474741 commented
@kolinwei

2021-10-09 07:55 UTC, kolinwei requested changes

2021-10-09 07:55 UTC, kolinwei commented on framework/api/nn/test_cosinesimilarity.py
> +def test_relu():
test_relu和上面的test_cosinesimilarity_base有啥区别？需要补充一些测试case，包括不同输入下的，不同axis下的。

2021-10-09 11:24 UTC, gsq7474741 commented on framework/api/nn/test_cosinesimilarity.py
> +def test_relu():
请问codestyle ci报cannot create directory at 'models/PaddleSlim/CI/Slim_CI_all_case/p1_api_case_static': No space left on device这个错怎么办呀

2021-10-09 11:27 UTC, gsq7474741 commented on framework/api/nn/test_cosinesimilarity.py
> +def test_relu():
@kolinwei 已经更新第二版，增加了各种测试实例

2021-10-11 03:00 UTC, DDDivano reviewed
可以增加一下 axis为负值的Case

2021-10-11 03:00 UTC, DDDivano requested changes
可以增加一下 axis为负值的Case

2021-10-11 03:05 UTC, kolinwei requested changes

2021-10-11 03:05 UTC, kolinwei commented on framework/api/nn/test_cosinesimilarity.py
> +    value
doc部分详细描述下该测试用例的验证点，测试输入，语气结果等，通过doc部分可以清除的知晓该用例的测试点。

2021-10-11 04:26 UTC, gsq7474741 commented on framework/api/nn/test_cosinesimilarity.py
> +    value
验证点要写死吗，现在是随机生成的

2021-10-11 04:26 UTC, gsq7474741 commented on framework/api/nn/test_cosinesimilarity.py
> +    value
@kolinwei

2021-10-11 05:04 UTC, kolinwei requested changes

2021-10-11 05:04 UTC, kolinwei commented on framework/api/nn/test_cosinesimilarity.py
> +    value
随机生成的只是输入的内容吧，但是输入的类型，纬度等都是不变的，比如：验证两个二维的float类型tensor在第零维的余弦相似度就是一个验证点。其他比如三维的，一个二维一个三维的，等等，同时可以变化下输入类型，

2021-10-11 05:04 UTC, gsq7474741 commented on framework/api/nn/test_cosinesimilarity.py
> +    value
@kolinwei 已更新第三版

2021-10-11 06:19 UTC, gsq7474741 commented
@kolinwei 感谢建议，已更新v4，请审阅

2021-10-12 03:14 UTC, kolinwei commented
> @kolinwei 感谢建议，已更新v4，请审阅

可以再加一些异常的case，比如axis为-1，axis比输入的纬度大等。

2021-10-12 07:26 UTC, gsq7474741 commented
> > @kolinwei 感谢建议，已更新v4，请审阅
> 
> 可以再加一些异常的case，比如axis为-1，axis比输入的纬度大等。

obj.run的data能否输入多个参数呀

2021-10-12 14:00 UTC, gsq7474741 commented
@kolinwei @DDDivano 已更新v5，增加了三个异常情况

2021-10-13 03:57 UTC, kolinwei requested changes

2021-10-13 03:57 UTC, kolinwei commented on framework/api/nn/test_cosinesimilarity.py
> +    except ValueError:
异常捕获的地方需要在case里面验证抛出的异常类型和错误信息。

2021-10-13 06:26 UTC, gsq7474741 commented on framework/api/nn/test_cosinesimilarity.py
> +    except ValueError:
@kolinwei 已更新

2021-10-14 05:40 UTC, gsq7474741 commented
已更新 @kolinwei

2021-10-15 07:15 UTC, kolinwei approved these changes

2021-10-15 07:33 UTC, gsq7474741 commented
已更新 @DDDivano

2021-10-19 11:24 UTC, DDDivano approved these changes

2021-10-19 11:24 UTC, merged