[PaddlePaddle hackathon] add unsamplingnearest2D unittest #35964
PaddlePaddle/PaddleTest pull request #224
Opened 2021-10-09 04:12 UTC by GeYuYao-hub

### PR types
Others

### PR changes
Others

### Describe
- Task:[#35964](https://github.com/PaddlePaddle/Paddle/issues/35964) 
- add unsamplingnearest2D unittest

2021-10-09 04:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=224) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleTest?pullRequest=224) it.</sub>

2021-10-09 13:57 UTC, GeYuYao-hub commented
@kolinwei 请问这个linux -ci的报错怎么改呀，我觉得好像没什么问题也不知道哪里错了

2021-10-11 02:45 UTC, kolinwei commented
> @kolinwei 请问这个linux -ci的报错怎么改呀，我觉得好像没什么问题也不知道哪里错了
可以点开这个ci的链接看下log。显示是这个case运行出错了，提交前可以本地跑一下。
![image](https://user-images.githubusercontent.com/22165420/136726062-4dedd388-c8d3-4c45-8a4a-25584f3b8a9b.png)

2021-10-11 10:05 UTC, GeYuYao-hub commented
@kolinwei 佬，改好了~

2021-10-11 12:46 UTC, kolinwei requested changes

2021-10-11 12:46 UTC, kolinwei commented on framework/api/nn/test_upsamplingnearest2d.py
> +def test_upsamplingnearest2d():
test_upsamplingnearest2d和test_upsamplingnearest2d_base有啥区别，每个case需要验证不同的测试点

2021-10-11 12:46 UTC, kolinwei commented on framework/api/nn/test_upsamplingnearest2d.py
> +    obj.run(res=res, data=x, size=size, scale_factor=scale_factor, data_format=data_format)
补充更多的测试case，比如size(scale_factor)为其他类型输入时(tuple|Tensor)等。输入x的值包含负数等异常情况。

2021-10-11 12:46 UTC, kolinwei commented on framework/api/nn/test_upsamplingnearest2d.py
> +    """
doc部分详细描述下该测试用例的验证点，测试输入，预期结果等，通过doc部分可以清楚的知晓该用例的测试点。

2021-10-15 03:20 UTC, GeYuYao-hub commented
@kolinwei 请问为什么我的报错一直提示我说to_tense中出现了问题呢，是paddle内部出现bug了嘛，困惑好几天了，在群里也问了，但是没有合适的解决方案，需要大佬帮忙解决一下orz

2021-10-15 08:20 UTC, DDDivano commented
> @kolinwei 请问为什么我的报错一直提示我说to_tense中出现了问题呢，是paddle内部出现bug了嘛，困惑好几天了，在群里也问了，但是没有合适的解决方案，需要大佬帮忙解决一下orz

这个出错原因是这样的，测试框架默认传入类型为numpy的参数，会在底层转成Tensor。你这个报错是6，8两个Case，因为你传入了一个动态图的Tensor，底层框架的静态图没有这个函数，所以这就是报错的原因。如果一个API的参数支持Tensor类型的输入，只需要传入numpy即可，因为测试框架目的就是为了尽可能脱离paddle概念，方便补充测试用例。
对于Tensor类型param输入，也只需要传入numpy类型，但需要参考文档。
![image](https://user-images.githubusercontent.com/10734244/137455103-96bfcfd2-bb72-49cf-9070-e3f85fd953dd.png)
我给你改了一下，你可以参考一下。针对6，8两个Case。
首先指定no_grad_var 声明不参与反向的参数
![image](https://user-images.githubusercontent.com/10734244/137455339-224f5851-bc13-4340-808c-0e74404c8e84.png)
case这样写，传入numpy类型参数并显式声明type，目的是为了防止不同系统平台对numpy的转化类型diff。
![image](https://user-images.githubusercontent.com/10734244/137455735-f2be0d2f-02d6-48a9-a655-91755b0334a4.png)
![image](https://user-images.githubusercontent.com/10734244/137455751-0ee1fb05-5da5-4307-a752-6211cb73d7b9.png)

2021-10-15 08:44 UTC, DDDivano commented
> > @kolinwei 请问为什么我的报错一直提示我说to_tense中出现了问题呢，是paddle内部出现bug了嘛，困惑好几天了，在群里也问了，但是没有合适的解决方案，需要大佬帮忙解决一下orz
> 
> @GeYuYao-hub  这个出错原因是这样的，测试框架默认传入类型为numpy的参数，会在底层转成Tensor。你这个报错是6，8两个Case，因为你传入了一个动态图的Tensor，底层框架的静态图没有这个函数，所以这就是报错的原因。如果一个API的参数支持Tensor类型的输入，只需要传入numpy即可，因为测试框架目的就是为了尽可能脱离paddle概念，方便补充测试用例。 对于Tensor类型param输入，也只需要传入numpy类型，但需要参考文档。 ![image](https://user-images.githubusercontent.com/10734244/137455103-96bfcfd2-bb72-49cf-9070-e3f85fd953dd.png) 我给你改了一下，你可以参考一下。针对6，8两个Case。 首先指定no_grad_var 声明不参与反向的参数 ![image](https://user-images.githubusercontent.com/10734244/137455339-224f5851-bc13-4340-808c-0e74404c8e84.png) case这样写，传入numpy类型参数并显式声明type，目的是为了防止不同系统平台对numpy的转化类型diff。 ![image](https://user-images.githubusercontent.com/10734244/137455735-f2be0d2f-02d6-48a9-a655-91755b0334a4.png) ![image](https://user-images.githubusercontent.com/10734244/137455751-0ee1fb05-5da5-4307-a752-6211cb73d7b9.png)

2021-10-16 11:57 UTC, GeYuYao-hub commented
@kolinwei 佬~改好啦

2021-10-19 02:14 UTC, kolinwei approved these changes

2021-10-19 03:01 UTC, merged