[PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue
PaddlePaddle/PaddleTest pull request #228
Opened 2021-10-10 15:46 UTC by simuler

PR types

New features

PR changes

APIs

Describe

Task: #35961

add test of paddle.nn.ClipGradByValue

2021-10-10 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=228) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleTest?pullRequest=228) it.</sub>

2021-10-11 01:32 UTC, simuler commented
> PR types
> 
> New features
> 
> PR changes
> 
> 添加/framwork/api/nn/test_clip_grad_by_value.py
> 
> Describe
> 
> Task: #35961
> 
> add test of paddle.nn.ClipGradByValue

2021-10-11 02:56 UTC, DDDivano commented on framework/api/nn/test_clip_grad_by_value.py
> +obj = TestClipGradByValue(paddle.nn.ClipGradByValue)
这里 obj定义了为什么没有用到呢？

2021-10-11 03:33 UTC, simuler commented
您好，请问不定义这个obj可以吗？
另外，unittest和pytest都可以使用吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





 
@DDDivano commented on this pull request.
 
 
In framework/api/nn/test_clip_grad_by_value.py:
 &gt; +    return numpy_data, tensor_data + + +class TestClipGradByValue(APIBase): +    """ +    test +    """ + +    def hook(self): +        """ +        implement +        """ +        self.types = [np.float32, np.float64] + + +obj = TestClipGradByValue(paddle.nn.ClipGradByValue)  
这里 obj定义了为什么没有用到呢？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-11 05:10 UTC, DDDivano commented
> 您好，请问不定义这个obj可以吗？ 另外，unittest和pytest都可以使用吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleTest" ***@***.***&gt;; 发送时间:&nbsp;2021年10月11日(星期一) 上午10:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228) @DDDivano commented on this pull request. In framework/api/nn/test_clip_grad_by_value.py: &gt; + return numpy_data, tensor_data + + +class TestClipGradByValue(APIBase): + """ + test + """ + + def hook(self): + """ + implement + """ + self.types = [np.float32, np.float64] + + +obj = TestClipGradByValue(paddle.nn.ClipGradByValue) 这里 obj定义了为什么没有用到呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以不使用，不过需要把用不上的代码删掉。unittest和pytest 尽可能使用pytest

2021-10-11 06:31 UTC, simuler commented
收到，非常感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 中午1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





  
您好，请问不定义这个obj可以吗？ 另外，unittest和pytest都可以使用吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleTest" @.&gt;; 发送时间:&nbsp;2021年10月11日(星期一) 上午10:56 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228) @DDDivano commented on this pull request. In framework/api/nn/test_clip_grad_by_value.py: &gt; + return numpy_data, tensor_data + + +class TestClipGradByValue(APIBase): + """ + test + """ + + def hook(self): + """ + implement + """ + self.types = [np.float32, np.float64] + + +obj = TestClipGradByValue(paddle.nn.ClipGradByValue) 这里 obj定义了为什么没有用到呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
可以不使用，不过需要把用不上的代码删掉。unittest和pytest 尽可能使用pytest
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-14 00:54 UTC, simuler commented
PR types

New features

PR changes

APIs

Describe

Task: #35961

add code annotation of paddle.nn.ClipGradByValue

2021-10-14 11:18 UTC, kolinwei requested changes

2021-10-14 11:18 UTC, kolinwei commented on framework/api/nn/test_clip_grad_by_value.py
> +        paddle_clip(paddle_data)
增加下min和max相等情况下的case，输入为除了float32和float64外其他类型的case

2021-10-15 11:57 UTC, simuler commented on framework/api/nn/test_clip_grad_by_value.py
> +        paddle_clip(paddle_data)
你好，已经增加min和max相等的case，输入为float16类型的case

2021-10-19 02:17 UTC, kolinwei requested changes

2021-10-19 02:17 UTC, kolinwei commented on framework/api/nn/test_clip_grad_by_value.py
> +        paddle_clip(paddle_data)
处理异常时校验下框架抛出的异常信息，在不同异常下抛出的是不同的，这个需要校验下

2021-10-20 14:12 UTC, simuler commented
不好意思，麻烦您可以详细说明一下
这个捕获异常部分的代码具体什么问题吗？

源码当中遇到这种情况是报的AssertionError。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





 
@kolinwei requested changes on this pull request.
 
 
In framework/api/nn/test_clip_grad_by_value.py:
 &gt; +        clip_min = None +        clip_max = 1.0 +    Changes: +        clip_max: 1.0 -&gt; -1.0 +    Expected Results: +        The output of ClipGradByValue implemented by numpy and paddle should be equal. +    """ +    shape = [10, 10] +    length = 4 +    clip_min = None +    clip_max = -1.0 +    np_data, paddle_data = generate_test_data(length, shape) + +    with pytest.raises(AssertionError): +        paddle_clip = paddle.nn.ClipGradByValue(clip_max, clip_min) +        paddle_clip(paddle_data)  
处理异常时校验下框架抛出的异常信息，在不同异常下抛出的是不同的，这个需要校验下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-21 12:30 UTC, kolinwei commented
> 不好意思，麻烦您可以详细说明一下 这个捕获异常部分的代码具体什么问题吗？ 源码当中遇到这种情况是报的AssertionError。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleTest" ***@***.***&gt;; 发送时间:&nbsp;2021年10月19日(星期二) 上午10:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228) @kolinwei requested changes on this pull request. In framework/api/nn/test_clip_grad_by_value.py: &gt; + clip_min = None + clip_max = 1.0 + Changes: + clip_max: 1.0 -&gt; -1.0 + Expected Results: + The output of ClipGradByValue implemented by numpy and paddle should be equal. + """ + shape = [10, 10] + length = 4 + clip_min = None + clip_max = -1.0 + np_data, paddle_data = generate_test_data(length, shape) + + with pytest.raises(AssertionError): + paddle_clip = paddle.nn.ClipGradByValue(clip_max, clip_min) + paddle_clip(paddle_data) 处理异常时校验下框架抛出的异常信息，在不同异常下抛出的是不同的，这个需要校验下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以参考https://github.com/PaddlePaddle/PaddleTest/pull/223

2021-10-22 07:15 UTC, simuler commented
你好，我参考#223捕获了所有Exception
打印捕获到的异常如下图所示，麻烦可以看下什么情况吗？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月21日(星期四) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





  
不好意思，麻烦您可以详细说明一下 这个捕获异常部分的代码具体什么问题吗？ 源码当中遇到这种情况是报的AssertionError。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleTest" @.&gt;; 发送时间:&nbsp;2021年10月19日(星期二) 上午10:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228) @kolinwei requested changes on this pull request. In framework/api/nn/test_clip_grad_by_value.py: &gt; + clip_min = None + clip_max = 1.0 + Changes: + clip_max: 1.0 -&gt; -1.0 + Expected Results: + The output of ClipGradByValue implemented by numpy and paddle should be equal. + """ + shape = [10, 10] + length = 4 + clip_min = None + clip_max = -1.0 + np_data, paddle_data = generate_test_data(length, shape) + + with pytest.raises(AssertionError): + paddle_clip = paddle.nn.ClipGradByValue(clip_max, clip_min) + paddle_clip(paddle_data) 处理异常时校验下框架抛出的异常信息，在不同异常下抛出的是不同的，这个需要校验下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
可以参考#223
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-25 07:10 UTC, simuler commented
你好，我参考#223捕获了所有Exception
代码和打印捕获到的异常如下图所示，麻烦可以看下什么情况吗？








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月21日(星期四) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





  
不好意思，麻烦您可以详细说明一下 这个捕获异常部分的代码具体什么问题吗？ 源码当中遇到这种情况是报的AssertionError。
 …
 ------------------ 原始邮件 ------------------ 发件人: "PaddlePaddle/PaddleTest" @.&gt;; 发送时间: 2021年10月19日(星期二) 上午10:18 @.&gt;; @.@.&gt;; 主题: Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228) @kolinwei requested changes on this pull request. In framework/api/nn/test_clip_grad_by_value.py: &gt; + clip_min = None + clip_max = 1.0 + Changes: + clip_max: 1.0 -&gt; -1.0 + Expected Results: + The output of ClipGradByValue implemented by numpy and paddle should be equal. + """ + shape = [10, 10] + length = 4 + clip_min = None + clip_max = -1.0 + np_data, paddle_data = generate_test_data(length, shape) + + with pytest.raises(AssertionError): + paddle_clip = paddle.nn.ClipGradByValue(clip_max, clip_min) + paddle_clip(paddle_data) 处理异常时校验下框架抛出的异常信息，在不同异常下抛出的是不同的，这个需要校验下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
可以参考#223
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-27 03:23 UTC, kolinwei commented
我看不到你发的图，具体是什么问题呢

2021-10-27 10:12 UTC, simuler commented
我运行以下代码，打印出来什么也没有
try:
&nbsp; clip1 = paddle.nn.ClipGradByvalue(max= -1)
except Exception as e1:
	print('except1:',e1)
打印出来是空格，什么也没有，就像下面
except1：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月27日(星期三) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





 
我看不到你发的图，具体是什么问题呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-28 14:05 UTC, kolinwei commented
> paddle.nn.ClipGradByvalu

换个其他的异常输入呢，不应该是空格呀

2021-10-28 14:20 UTC, simuler commented
这是捕捉两个异常的情况
try:
&nbsp; clip1 = paddle.nn.ClipGradByvalue(max= -1)
except Exception as e1:
	print('except1:',e1)


try:
&nbsp; clip2 = paddle.nn.ClipGradByValue(max='1')
except Exception as e2:
	print('except2:',e2)


打印出来第一个是空格，第二个是错误
except1：
except2: '&gt;' not supported between instance of 'str' and 'float'





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleTest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 晚上10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleTest] [PaddlePaddle hackathon] add test of paddle.nn.ClipGradByValue (#228)





  
paddle.nn.ClipGradByvalu
  
换个其他的异常输入呢，不应该是空格呀
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-29 05:22 UTC, kolinwei approved these changes

2021-10-29 11:16 UTC, merged