[PaddlePaddle Hackathon] 第37题 AlphaDropout单测
PaddlePaddle/PaddleTest pull request #232
Opened 2021-10-11 08:42 UTC by iverxin

## PR types
Others

## PR changes
 Others

## Describe
Task: #35968
1. 增加AlphaDropout的单元测试文件
2. 重写父类的run_base函数，确保动态图和静态图的测试时产生的随机数相同

2021-10-13 05:12 UTC, iverxin commented
1. 在测试子类中重写了_base_run, run等函数，以确保动态图和静态图生成的随机mask一致

2021-10-14 11:12 UTC, kolinwei requested changes

2021-10-14 11:12 UTC, kolinwei commented on framework/api/nn/test_alpha_dropout.py
> +    """
doc中写明测试点，验证的内容，

2021-10-15 06:00 UTC, iverxin commented on framework/api/nn/test_alpha_dropout.py
> +    """
已添加~

2021-10-15 10:44 UTC, kolinwei requested changes

2021-10-15 10:44 UTC, kolinwei commented on framework/api/nn/test_alpha_dropout.py
> +    obj.exception(etype=TypeError, mode="python", data=x, p="1")
当前测试case的输入维度均为[2,3],可以增加下大维度下的测试，比如5维、10维

2021-10-19 02:22 UTC, kolinwei requested changes

2021-10-19 02:22 UTC, kolinwei commented on framework/api/nn/test_alpha_dropout.py
> +    x = randtool("float", 0, 2, [2, 3])
case中输入的值值可以设的大一些，不必每个都是0到2之间

2021-10-19 07:56 UTC, iverxin commented on framework/api/nn/test_alpha_dropout.py
> +    x = randtool("float", 0, 2, [2, 3])
Done

2021-10-19 10:28 UTC, kolinwei approved these changes

2021-10-21 07:41 UTC, iverxin commented
请问什么时候可以merge呢~

2021-10-22 11:04 UTC, merged