[PaddlePaddle Hackathon] 第35题 RNN测试
PaddlePaddle/PaddleTest pull request #246
Opened 2021-10-14 06:47 UTC by iverxin

## PR types
Others

## PR changes
Others

## Describe
Task: https://github.com/PaddlePaddle/Paddle/issues/35970
1. 修改apibase中对于返回结果为tuple的检测。
2. 增加RNN的base测试。

2021-10-21 07:39 UTC, iverxin commented
hello~

2021-10-27 03:52 UTC, kolinwei requested changes

2021-10-27 03:52 UTC, kolinwei commented on framework/api/nn/test_rnn_float64.py
> +    np_cell = SimpleRNNCell(4, 8)
SimpleRNNCell的shape需要变化下，不能每个case都是一样的，可以弄大一些。

2021-10-27 03:52 UTC, kolinwei commented on framework/api/nn/test_rnn_float64.py
> +    obj.run(res, data=inputs, cell=cell, time_major=True)
test_rnn.py和test_rnn_flost64合成一个文件吧

2021-10-27 07:22 UTC, iverxin commented on framework/api/nn/test_rnn_float64.py
> +    np_cell = SimpleRNNCell(4, 8)
Done~

2021-10-27 07:23 UTC, iverxin commented on framework/api/nn/test_rnn_float64.py
> +    obj.run(res, data=inputs, cell=cell, time_major=True)
Done

2021-11-01 06:57 UTC, DDDivano approved these changes

2021-11-01 06:59 UTC, merged