[PaddlePaddle Hackathon] add paddle.nn.ClipGradByNorm单测
PaddlePaddle/PaddleTest pull request #278
Opened 2021-10-25 08:15 UTC by justld

PR types：New features

PR changes：APIs

Describe

Task: #35962

添加paddle.nn.ClipGradByNorm单测，PaddleTest\framework\api\nn\test_clip_grad_by_norm.py

2021-10-27 03:46 UTC, kolinwei requested changes

2021-10-27 03:46 UTC, kolinwei commented on framework/api/nn/test_clip_grad_by_norm.py
> +            pass
使用apibase里面的exception方法

2021-10-27 07:41 UTC, justld commented on framework/api/nn/test_clip_grad_by_norm.py
> +            pass
您好，apibase的exception运行时，425行代码 _check_params函数会把data通过paddle.to_tensor转换成tensor，但是paddle.nn.ClipGradByGlobalNorm实例调用时传入的参数类型是list[tuple, tuple, tuple...]，会导致运行出错，所以才使用try except这种方式捕获异常。如果使用exception捕获异常的话，应该怎么修改呢？

2021-10-29 03:14 UTC, DDDivano commented on framework/api/nn/test_clip_grad_by_norm.py
> +            pass
这里直接使用 with pytest.raises 方式吧

2021-10-29 05:37 UTC, justld commented on framework/api/nn/test_clip_grad_by_norm.py
> +            pass
您好，已经修改了。

2021-10-29 14:54 UTC, justld commented on framework/api/nn/test_clip_grad_by_norm.py
> +            pass
不好意思，之前的没通过ci，现在已经OK了。

2021-11-01 10:01 UTC, kolinwei approved these changes

2021-11-03 04:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=278) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=278) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: justld<br/>:white_check_mark: DDDivano<br/>:x: kolinwei<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleTest?pullRequest=278) it.</sub>

2021-11-03 09:08 UTC, merged