[PaddlePaddle Hackathon] 第34题 BiRNN测试
PaddlePaddle/PaddleTest pull request #288
Opened 2021-10-28 13:46 UTC by iverxin

## PR types
Others

## PR changes
Others

## Describe
Task: https://github.com/PaddlePaddle/Paddle/issues/35971
1. 增加BiRNN的单元测试，包括动态图、静态图、梯度、不同的范围。

2021-11-01 10:08 UTC, kolinwei requested changes

2021-11-01 10:08 UTC, kolinwei commented on framework/api/nn/test_birnn.py
> +    测试默认参数
描述中把用例的测试的功能点、输入、预期输入等描述清楚

2021-11-01 10:08 UTC, kolinwei commented on framework/api/nn/test_birnn.py
> +    obj64.run(res, data=inputs, cell_fw=paddle_cell_fw, cell_bw=paddle_cell_bw, time_major=True)
需要增加一些异常用例，

2021-11-02 07:50 UTC, iverxin commented on framework/api/nn/test_birnn.py
> +    obj64.run(res, data=inputs, cell_fw=paddle_cell_fw, cell_bw=paddle_cell_bw, time_major=True)
Done

2021-11-03 04:40 UTC, kolinwei requested changes

2021-11-03 04:40 UTC, kolinwei commented on framework/api/nn/test_birnn.py
> +
TestBiRNN64 和TestBiRNN(APIBase)可以合成一个类吧，支持多种type

2021-11-03 05:55 UTC, iverxin commented on framework/api/nn/test_birnn.py
> +
我是这样考虑的：
在调用baserun的时候测试框架会遍历self.typeps下的所有数据类型。但是在apibase里没有对paddle的默认数据类型进行设置，并且也没有对输入的网络权重类型进行统一的数据类型转换。
所以在不改变原有的测试框架下，我想到的解决办法就是写两个类，或者像test_conv1d的测试一样写两个文件分别测试float64和float32。

2021-11-04 09:45 UTC, kolinwei approved these changes, later dismissed

2021-11-08 07:50 UTC, DDDivano approved these changes
LGTM

2021-11-08 07:50 UTC, merged