[PaddlePaddle Hackathon] 34.Add test of nn.BeamSearchDecoder v0.1
PaddlePaddle/PaddleTest pull request #291
Opened 2021-10-29 15:32 UTC by ZS-Yan

[PaddlePaddle Hackathon] 在 Paddle 中新增 paddle.nn.BeamSearchDecoder 的测试用例

PR types

New features

PR changes

APIs

Describe

    Task: #35960

    Add test of nn.BeamSearchDecoder v0.1

2021-10-29 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/PaddleTest?pullRequest=291) <br/>All committers have signed the CLA.

2021-10-29 15:55 UTC, jelly2187 commented
@kolinwei

2021-11-01 10:15 UTC, kolinwei requested changes

2021-11-01 10:15 UTC, kolinwei commented on framework/api/nn/test_beamsearchdecoder.py
> +obj = TestBeamSearchDecoder(paddle.nn.BeamSearchDecoder)
这个obj没有用？

2021-11-01 10:15 UTC, kolinwei commented on framework/api/nn/test_beamsearchdecoder.py
> +            raise Exception
增加更多异常类的测试用例，start_token, end_token等都可以设置异常，

2021-11-01 13:03 UTC, ZS-Yan commented on framework/api/nn/test_beamsearchdecoder.py
> +obj = TestBeamSearchDecoder(paddle.nn.BeamSearchDecoder)
原先是用来调用paddle框架里的随机种子的，已修改

2021-11-01 13:03 UTC, ZS-Yan commented on framework/api/nn/test_beamsearchdecoder.py
> +            raise Exception
已更新！

2021-11-02 12:15 UTC, kolinwei approved these changes

2021-11-08 07:56 UTC, merged