【PaddlePaddle Hackathon】36、在 Paddle 中新增 paddle.nn.RNNCellBase 的测试用例
PaddlePaddle/PaddleTest pull request #301
Opened 2021-11-02 16:27 UTC by gsq7474741

### PR types

New features
### PR changes

tests
### Describe

- Add test of nn.RNNCellBase
- Task: https://github.com/PaddlePaddle/Paddle/issues/35969

2021-11-02 19:35 UTC, gsq7474741 commented
@kolinwei

2021-11-03 04:46 UTC, kolinwei requested changes

2021-11-03 04:46 UTC, kolinwei commented on framework/api/nn/test_rnncellbase.py
> +            raise Exception
增加init_value为负和更大值的测试，shape为错误值的情况

2021-11-03 06:17 UTC, gsq7474741 commented on framework/api/nn/test_rnncellbase.py
> +            raise Exception
已修改

2021-11-03 06:25 UTC, gsq7474741 commented on framework/api/nn/test_rnncellbase.py
> +            raise Exception
fixed @kolinwei

2021-11-04 04:04 UTC, gsq7474741 commented
@kolinwei 已更新

2021-11-04 09:25 UTC, kolinwei approved these changes

2021-11-08 07:52 UTC, merged